- name: Install dependencies
  hosts: all
  roles:
    - geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: datadog

- name: Deploy application
  hosts: all
  gather_facts: no
  tasks:
    - name: Create a Docker environment file
      ansible.builtin.template:
        src: templates/.env.j2
        dest: .env
        mode: 0644
    - name: Run container
      community.docker.docker_container:
        name: redmine
        image: redmine:4.2.3-alpine
        published_ports: '{{ app_port }}:3000'
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env_file: .env

- name: Install datadog
  hosts: webservers
  gather_facts: no
  roles:
    - { role: datadog.datadog, become: yes }
  vars:
    datadog_api_key: '{{ datadog_api_key }}'
    datadog_site: '{{ datadog_site }}'
    datadog_checks: '{{ datadog_checks }}'
