ansible_user: "root"

db_host: "{{ vault_db_host }}"
db_port: "{{ vault_db_port }}"
db_name: "{{ vault_db_name }}"
db_username: "{{ vault_db_username }}"
db_password: "{{ vault_db_password }}"

dd_api_key: "{{ vault_dd_api_key }}"
dd_site: "{{ vault_dd_site }}"
dd_checks:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: "http://localhost:3000"
        timeout: 5
        method: GET
